[tools]
python = '3.11'
ruby = '3.3'
node = '20'
# gcloud = "latest"
zig = "latest"
rust = "latest"
bun = "latest"

# Aqua backend
"aqua:kubernetes/kubectl" = "1.33.2"
"aqua:helm/helm" = "v3.18.4"
"aqua:hashicorp/terraform" = "1.12.2"
"aqua:gruntwork-io/terragrunt" = "v0.83.1"

# Cargo
"cargo:bob-nvim" = "4.1.1"

# Github backend
"github:FiloSottile/age" = "v1.2.0"
"github:sharkdp/bat" = "v0.25.0"
"github:sharkdp/fd" = "v10.2.0"
"github:BurntSushi/ripgrep" = { version = "14.1.1", exe = "rg" }
"github:eza-community/eza" = "v0.22.0"
"github:jqlang/jq" = "jq-1.8.1"
"github:mikefarah/yq" = "v4.45.4"
"github:jesseduffield/lazygit" = "v0.47.2"
"github:astral-sh/uv" = "0.7.20"
"github:getsops/sops" = "v3.10.2"
"github:ajeetdsouza/zoxide" = "0.9.8"
"github:starship/starship" = "v1.23.0"
"github:ducaale/xh" = "v0.24.1"
"github:zellij-org/zellij" = "v0.42.2"
"github:dandavison/delta" = "0.18.2"
"github:siderolabs/talos" = { version = "v1.10.5", rename_exe = "talosctl" }
"github:jj-vcs/jj" = "v0.31.0"
"github:mongodb-js/mongosh" = "2.5.5"
"github:rossmacarthur/sheldon" = "0.8.4"
"github:antonmedv/fx" = "37.0.1"
"github:yt-dlp/yt-dlp" = { version = "2025.07.21", rename_exe = "yt" }
"github:charmbracelet/crush" = "v0.4.0"
"github:tailwindlabs/tailwindcss" = "v4.1.12"
"github:jdx/fnox" = "v1.7.0"

# NPM backend
"npm:opencode-ai" = "latest"

[env]
MISE_NPM_BUN = true
EDITOR = "nvim"

watchexec = "latest"

[settings]
experimental = true
